### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by jbrown9100** [githubschool-jobro/caption-this#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by cs4852002** [comment]
Comment

**Comment by alexkim12345** [comment]
Comment

**Comment by bichen** [comment]
This is a comment

**Comment by jameskim03** [comment]
Excited to work with GitHub

**Comment by BibhuA** [comment]
Hi

**Comment by makwei88** [comment]
comment #1

**Comment by jbrown9100** [comment]
GitHub is awesome.

**Comment by derekpeng3** [comment]
comment

**Comment by ibteck** [comment]
Excited to learn!

**Comment by tangallan** [comment]
hi

**Comment by poco547gh** [comment]
Looking forward to the lab

**Comment by jnehmeLASC** [comment]
@jameskim03

**Comment by buommo** [comment]
thank you,

**Comment by alanlayson** [comment]
Im in.

**Comment by LASC-Pvu** [comment]
comment
